name: node.js ci -with cache - composite

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: Build Node
          uses: k-t-or2/GHA.workflows/.github/actions/build-node@main 